config/routes.rb
Rails.application.routes.draw do
  get 'my_portfolio', to: "users#my_portfolio"
  get 'my_friends', to: "users#my_friends"
  devise_for :users
  root "welcome#index"
  get 'search_stock', to: "stocks#search"
  get 'search_user', to: "friendships#search"
  resources :user_stocks, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [ :show ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  validate :befriendable

  def befriendable
    errors.add(:users, "can't befriend themselves") if befriending_oneself
    errors.add(:users, "are friends already") if is_friend
  end

  def befriending_oneself
    user_id == friend_id
  end

  def is_friend
    !Friendship.find_by(user_id: user_id, friend_id: friend_id).nil?
  end
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks, dependent: :destroy
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true, uniqueness: true

  def self.new_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex[:public_key],
      secret_token: Rails.application.credentials.iex[:secret_key],
      endpoint: 'https://cloud.iexapis.com/v1'
    )
    begin
      stock = client.quote(ticker_symbol.upcase)
      new(
        ticker: stock.symbol,
        name: stock.company_name,
        last_price: stock.latest_price
      )
    rescue => exception
      nil
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Account"
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
  validate :no_repeat, :tracked_stocks_limit

  def no_repeat
    if UserStock.find_by(user_id: user_id, stock_id: stock_id)
      errors.add(:stock, "already associated to current user" )
    end
  end

  def tracked_stocks_limit
    if UserStock.where(user_id: user_id).count >= 10
      errors.add(:users, "cannot track more than 10 stocks at a time")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def search
    email = params[:email].strip
    @user = User.find_by(email: email)
    respond_to do |format|
      if @user
        @friendship = current_user.friendships.build(friend_id: @user.id )
        flash.now[:alert] = "Can't befriend yourself" if @friendship.befriending_oneself
        @friend = nil if !flash.now[:alert].nil?
      else
        flash.now[:alert] = email == "" ? "Email can't be blank" : "User does not exist"
      end
      format.js { render partial: "friends/friend.js" }
    end
  end

  def create
    @user = User.find_by(id: params[:id])
    respond_to do |format|
      if @user
        begin
          current_user.friends << @user
          flash.now[:success] = "You are now following #{@user.full_name}"
        rescue => exception
          flash.now[:alert] = exception.message.sub("Validation failed: ", "")
          @user = nil
        end
      else
        flash.now[:alert] = "User does not exist"
      end
      format.js {render partial: "friendships/friendship.js"}
    end
  end

  def destroy
    friendship = Friendship.find_by(user_id: current_user.id, friend_id: params[:id])
    friend = User.find(params[:id])
    if friendship
      friendship.destroy
      flash[:success] = "Stopped following #{friend.email}"
    else
      flash[:alert] = "Users are not friends"
    end
    redirect_to my_friends_path
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    respond_to do |format|
      if params[:ticker].empty?
        flash.now[:alert] = "Input cannot be blank"
      else
        @stock = user_tracked_stock(params[:ticker])
      end
      format.js { render partial: 'stock.js' }
    end
  end

  private
  def user_tracked_stock(ticker)
    stock = nil
    if current_user.stocks.find_by(ticker: ticker)
      flash.now[:alert] = "That stock is part of your portfolio already"
    else
      stock = Stock.new_lookup(ticker)
      flash.now[:alert] = "Ticker symbol does not exist in database" if stock.nil?
    end
    stock
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    ticker = params[:ticker]
    @stock = Stock.find_by(ticker: ticker) || Stock.new_lookup(ticker)
    respond_to do |format|
    if @stock
      begin
        current_user.stocks << @stock
        flash.now[:sucess] = "Successfully added #{@stock.name} to your portfolio"
      rescue => exception
        flash.now[:alert] = exception.message.sub("Validation failed: ", "")
        @stock = nil
      end
    else
      flash.now[:alert] = "Invalid ticker symbol"
    end
     format.js {render partial: "tracked_stocks.js"}
    end
  end

  def destroy
    record = UserStock.find_by(user_id: current_user.id, stock_id: params[:id])
    if record.destroy
      flash[:sucess] = "Stock successfully removed"
    else
      flash[:alert] = "User does not have that stock in their portfolio"
    end
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @stocks = current_user.stocks
  end

  def my_friends
    @friends = current_user.friends
  end

  def show
    @user = User.find(params[:id])
    @stocks = @user.stocks
    @is_friend = current_user.friends.find_by(email: @user.email )
    render "show"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/_friend.html.erb
<%= render "layouts/messages" %>

<% if @user %>
  <div class="card justify-content-center" style="width: 18rem;">
    <div class="card-body d-flex flex-column">
      <h5 class="card-title"><%= @user.full_name %></h5>
      <p class="card-text text-center"><%= @user.email %></p>
    </div>

    <div class="d-flex justify-content-center m-2">
      <%if current_user != @user%>
        <div class="container d-flex justify-content-center">
          <% if is_friend %>
            <span class="badge bg-secondary d-flex align-items-center">Already friends</span>
          <% else %>
            <%= link_to "Add friend", friendships_path(id: @user.id), method: :post, class: "btn btn-sm btn-success", remote: true %>
          <% end %>
        </div>
      <% end %>

      <% if current_page?(search_user_path)%>
      <div class="container d-flex justify-content-center">
        <%= link_to "View profile", user_path(@user), class: "btn btn-sm btn-success"%>
      </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/friends/_friend.js.erb
$('.alert').remove()
$('#result .card').remove()
$('#result').append("<%= j render partial: 'friends/friend.html', locals: {is_friend: @friendship.is_friend} %>")
$('#email').val("")

app/views/friendships/_friendship.html.erb
<% if friend %>
    <tr>
        <th scope="row"><%= friend.first_name %></th>
        <td><%= friend.last_name %></td>
        <td><%= friend.email %></td>
        <td class="d-flex justify-content-between">
            <div ><%=link_to "Remove", friendship_path(friend), method: :delete, class: "btn btn-sm btn-warning", data:{confirm: "Are you sure?"}%></div class= "col">
            <div ><%=link_to "Profile", user_path(friend), class: "btn btn-sm btn-success"%></div class= "col">
        </td>
    </tr>
<% end %>

app/views/friendships/_friendship.js.erb
if($("#friends-table-body").length > 0){
    $("#friends-table-body").append("<%= j render partial: 'friendship.html', locals: { friend: @user } %>")
    if ($("table").length === 0){
        <% @friends = [ @friend ]%>
        $("body").append("<%= j render partial: "friendships_table"%>")
    }

    $('#result .card').remove()
    $('.alert').remove()
    $('#result').prepend("<%= j render partial: 'layouts/messages'%>")
}
else{
    $('#user-info .card').remove()
    $('#user-info').append("<%= j render partial: "friends/friend.html", locals:{ is_friend: true}%>")
}

app/views/friendships/_friendships_table.html.erb
<div class="row justify-content-center">
    <div class="col-6">
        <table class="table table-dark table-hover">
                <thead>
                    <tr>
                    <th scope="col">First name</th>
                    <th scope="col">Last name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody id= "friends-table-body">
                    <% @friends.each do |friend| %>
                        <%= render "friendships/friendship.html", friend: friend %>
                    <% end %>
                </tbody>
        </table>
    </div>
</div>

app/views/layouts/_messages.html.erb
<% if !flash.keys.empty? %>
    <div class="alert alert-<%= flash[:alert] ? "warning" : "success" %> alert-dismissible fade show mt-3" role="alert">
        <% flash.each do |key, msg| %>
            <strong><%= msg %></strong>
        <% end %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark navbar-expand-lg bg-dark mb-3" id="navbar">
  <div class="container">
    <%= link_to "Finance Tracker", root_path, class: "navbar-brand"%>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Portfolio", my_portfolio_path, class: "nav-link #{'active' if current_page?(my_portfolio_path)}" %>
        </li>
        <li class="nav-item">
          <%= link_to "Friends", my_friends_path, class: "nav-link #{'active' if current_page?(my_friends_path)}" %>
        </li>
      </ul>
      <ul class = "navbar-nav mb-lg-0">
        <% if user_signed_in? %>
          <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle <%= 'active' if request.path =~ /users/%>" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.full_name%>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to "Account settings", edit_user_registration_path, class: "dropdown-item"%></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item"%></li>
            </ul>
          </div>
        <% else %>
            <li class = "nav-item"><%= link_to "Log In", new_user_session_path, class: "nav-link"%></li>
            <li class= "nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link"%></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_stock.html.erb
<%= render "layouts/messages" %>

<% if @stock%>
  <div class="card justify-content-center" style="width: 18rem;">
    <div class="card-body d-flex justify-content-around">
      <h5 class="card-title"><%= stock.ticker %></h5>
      <p class="card-text text-center"><%= stock.name %></p>
      <p class="card-text"><strong><%= stock.last_price %></strong></p>
    </div>
      <%= link_to "Add to portfolio", user_stocks_path(user: current_user, ticker: stock.ticker), method: :post, class: "btn btn-success", remote: true %>
  </div>
<% end %>

app/views/stocks/_stock.js.erb
$('.alert').remove()
$('#result .card').remove()
$('#result').append("<%= j render partial: 'stocks/stock.html', locals: {stock: @stock} %>")
$('#ticker').val("")

app/views/user_stocks/_table_tracked_stocks.html.erb
<div class="row justify-content-center">
    <div class="col-6">
        <table class="table table-dark table-hover">
                <thead>
                    <tr>
                    <th scope="col">Ticker</th>
                    <th scope="col">Name</th>
                    <th scope="col">Price</th>
                    <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody id= "stocks-table-body">
                    <% @stocks.each do |stock|%>
                        <%= render "user_stocks/tracked_stocks.html", stock: stock, user: user%>
                    <% end %>
                </tbody>
        </table>
    </div>
</div>

app/views/user_stocks/_tracked_stocks.html.erb
<% if stock %>
    <tr id= "<%=stock.ticker%>">
        <th scope="row"><%= stock.ticker %></th>
        <td><%= stock.name %></td>
        <td><%= stock.last_price %></td>
        <td>
        <% if user != current_user && current_user.stocks.find_by(id: stock.id)  %>
            <span class= "badge bg-secondary">Tracking stock</span>
        <% elsif current_user.stocks.find_by(id: stock.id)%>
            <%= link_to "Remove", user_stock_path(stock), method: :delete, class: "btn btn-danger", data:{confirm: "Are you sure?"}%>
        <% else %>
            <%= link_to "Add to portfolio", user_stocks_path(user: current_user, ticker: stock.ticker), method: :post, class: "btn btn-success", remote: true %>
        <% end %>
        </td>
    </tr>
<% end %>

app/views/user_stocks/_tracked_stocks.js.erb
$('.alert').remove()
if($("#result").length > 0){
    $('#result .card').remove()
    $("#stocks-table-body").prepend("<%= j render partial: 'tracked_stocks.html', locals: { stock: @stock, user: current_user } %>")

    if ($("table").length === 0){
        <% @stocks = [@stock]%>
        $("body").append("<%= j render partial: "table_tracked_stocks", locals: {user: current_user }%>")
    }

    $('#result').prepend("<%= j render partial: 'layouts/messages'%>")
}
else{
    $("#<%= @stock.ticker %>").remove()
    $("#user-stocks").prepend("<%= j render partial: 'layouts/messages'%>")
    $("#stocks-table-body").prepend("<%= j render partial: 'tracked_stocks.html', locals: { stock: @stock, user: @user } %>")
}

app/views/users/my_friends.html.erb
<h1>My Friends</h1>
<div class="mt-5">
    <h2 class="text-center">Search Users</h2>
    <%= form_with url:"search_user", method: :get, id: "searchUser", class:"row d-flex justify-content-center" do |f| %>
    <div class="col-md-6">
        <div class="input-group">
            <%= f.text_field :email, class: "form-control form-control-lg", placeholder: "User email" %>
            <%= image_submit_tag "search.svg", class: "btn btn-primary rounded-end"%>
        </div>
    </div>
    <% end %>
</div>

<div class="container d-flex flex-column align-items-center my-5" id="result">
</div>

<% if !@friends.empty? %>
 <%= render 'friendships/friendships_table' %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>
<div class="mt-5">
    <h2 class="text-center">Search Stocks</h2>
    <%= form_with url:"search_stock", method: :get, id: "searchStock", class:"row d-flex justify-content-center" do |f| %>
    <div class="col-md-6">
        <div class="input-group">
            <%= f.text_field :ticker, class: "form-control form-control-lg", placeholder: "Ticker symbol for company" %>
            <%= image_submit_tag "search.svg", class: "btn btn-primary rounded-end"%>
        </div>
    </div>
    <% end %>
</div>

<div class="container d-flex flex-column align-items-center my-5" id="result">
</div>

<% if !@stocks.empty? %>
 <%= render 'user_stocks/table_tracked_stocks', user: current_user %>
<% end %>

app/views/users/show.html.erb
<h1>Profile</h1>
<h2 class="mt-5 mb-2">User info</h2>

<div class="container d-flex flex-column align-items-center mb-5" id="user-info">
    <%= render 'friends/friend.html', is_friend: @is_friend %>
</div>

<h2>Stocks</h2>
<div id= "user-stocks">
    <% if !@stocks.empty? %>
        <%= render 'user_stocks/table_tracked_stocks', user: @user%>
    <% else %>
        <h3 class="lead">User is not tracking any stocks</h3>
    <% end %>
</div>

app/views/welcome/index.html.erb
<h1>Ashita no Joe</h1>

<%= link_to "Sign out", destroy_user_session_path, method: :delete %>